"use client";

import { useMemo, useState, type ReactNode } from "react";
import dynamic from "next/dynamic";
import { useFormatter, useNow, useTranslations } from "next-intl";
import { ActionIcon, Badge, Box, Button, Grid, Group, Stack, Text, Title, UnstyledButton } from "@mantine/core";
import { IconChevronRight, IconPlus, IconTrash } from "@tabler/icons-react";
import { api } from "~/trpc/react";
import type { CountryAnalysisEntry, CreatedAnalysis } from "~/server/api/routers/analysis";
import type { MapRegion } from "~/components/map/crisis-map";
import { resolveCountryConfig } from "~/lib/constants/country-config";
import { ANALYSIS_CADENCES, isStale, type AnalysisCadence } from "~/lib/analysis-view";

const CrisisMap = dynamic(() => import("~/components/map/crisis-map").then((m) => m.CrisisMap), {
  ssr: false,
  loading: () => <Box style={{ width: "100%", height: "100%", background: "var(--color-bg-muted)" }} />,
});

/** Country analyses are regenerated by the weekly pipeline job. */
const COUNTRY_CADENCE = "weekly";

/**
 * Insights -> Analysis landing: pick which analysis to open (the country's, or
 * one the team created over districts) or create a new one.
 */
export function AnalysisHome({
  countryId,
  countryName,
  country,
  created,
  loading,
  canCreate,
  canRemove,
  selector,
  onOpenCountry,
  onOpenCreated,
  onNew,
}: {
  countryId: string;
  countryName: string;
  country: CountryAnalysisEntry | null;
  created: CreatedAnalysis[];
  loading: boolean;
  canCreate: boolean;
  canRemove: boolean;
  selector: ReactNode;
  onOpenCountry: () => void;
  onOpenCreated: (c: CreatedAnalysis) => void;
  onNew: () => void;
}) {
  const t = useTranslations("analysis.home");
  const tc = useTranslations("analysis.cadence");
  const format = useFormatter();
  const now = useNow({ updateInterval: 60_000 });
  const utils = api.useUtils();
  const [confirming, setConfirming] = useState<string | null>(null);
  const remove = api.analysis.remove.useMutation({
    onSuccess: () => utils.analysis.scopes.invalidate(),
    onSettled: () => setConfirming(null),
  });

  const districts = api.locations.getAdminBoundaries.useQuery(
    { level: 2, countryId },
    { enabled: created.length > 0, staleTime: Infinity, refetchOnWindowFocus: false },
  );
  const regions = useMemo<MapRegion[]>(() => {
    const geo = new Map((districts.data ?? []).map((d) => [d.id, d.geometry]));
    return created.flatMap((c) =>
      c.locationIds
        .filter((id) => geo.get(id))
        .map((id) => ({
          id: `${c.id}-${id}`,
          geometry: geo.get(id) as MapRegion["geometry"],
          severity: "high" as const,
          title: c.name,
        })),
    );
  }, [created, districts.data]);
  const config = resolveCountryConfig(countryName);

  const cadenceLabel = (c: string) =>
    (ANALYSIS_CADENCES as readonly string[]).includes(c) ? tc(c as AnalysisCadence).toLowerCase() : c;
  const status = (generatedAt: string | null, cadence: string, enabled = true) => {
    if (!generatedAt) return { text: t("generating"), stale: false };
    const updated = t("updated", { relative: format.relativeTime(new Date(generatedAt), now) });
    return {
      text: enabled ? `${updated} · ${cadenceLabel(cadence)}` : `${updated} · ${t("paused")}`,
      stale: enabled && isStale(generatedAt, cadence, now),
    };
  };
  const countryStatus = country?.generatedAt
    ? status(country.generatedAt, COUNTRY_CADENCE)
    : { text: t("noCountryAnalysis"), stale: false };

  return (
    <Box>
      <Group justify="space-between" align="flex-end" mb={24} gap={12}>
        <Box>
          <Title order={2} c="var(--color-text-primary)" style={{ fontSize: 26, lineHeight: 1.15 }}>
            {t("title")}
          </Title>
          <Text c="var(--color-text-secondary)" mt={4} style={{ fontSize: 13 }}>
            {t("subtitle", { country: countryName })}
          </Text>
        </Box>
        <Group gap={8}>
          {selector}
          {canCreate && (
            <Button size="xs" color="dark" leftSection={<IconPlus size={14} />} onClick={onNew} data-testid="analysis-new">
              {t("new")}
            </Button>
          )}
        </Group>
      </Group>

      <Grid gutter={16}>
        <Grid.Col span={{ base: 12, md: 7 }}>
          <Stack gap={24}>
            <Box>
              <GroupLabel>{t("countryGroup")}</GroupLabel>
              <ScopeRow
                title={countryName}
                subtitle={t("wholeCountry")}
                status={countryStatus.text}
                stale={countryStatus.stale}
                onOpen={onOpenCountry}
                testId="analysis-scope-country"
              />
            </Box>

            <Box>
              <GroupLabel>{t("createdGroup")}</GroupLabel>
              {loading ? null : created.length === 0 ? (
                <Box p={20} style={{ border: "1px dashed var(--color-border-dark)" }} data-testid="analysis-created-empty">
                  <Text c="var(--color-text-secondary)" style={{ fontSize: 13 }}>
                    {canCreate ? t("createdEmpty") : t("createdEmptyReadOnly")}
                  </Text>
                </Box>
              ) : (
                <Stack gap={8}>
                  {created.map((c) => {
                    const s = status(c.generatedAt, c.cadence, c.enabled);
                    return (
                      <ScopeRow
                        key={c.id}
                        title={c.name}
                        subtitle={t("areas", { count: c.locationIds.length })}
                        status={s.text}
                        stale={s.stale}
                        generating={!c.generatedAt}
                        onOpen={() => onOpenCreated(c)}
                        testId={`analysis-scope-${c.id}`}
                        action={
                          canRemove ? (
                            confirming === c.id ? (
                              <Group gap={6} wrap="nowrap">
                                <Button
                                  size="compact-xs"
                                  color="red"
                                  loading={remove.isPending}
                                  onClick={() => remove.mutate({ id: c.id })}
                                  data-testid="analysis-remove-confirm"
                                >
                                  {t("remove")}
                                </Button>
                                <Button size="compact-xs" variant="default" onClick={() => setConfirming(null)}>
                                  {t("keep")}
                                </Button>
                              </Group>
                            ) : (
                              <ActionIcon
                                variant="subtle"
                                color="gray"
                                aria-label={t("removeLabel", { name: c.name })}
                                onClick={() => setConfirming(c.id)}
                                data-testid="analysis-remove"
                              >
                                <IconTrash size={16} />
                              </ActionIcon>
                            )
                          ) : null
                        }
                      />
                    );
                  })}
                </Stack>
              )}
            </Box>
          </Stack>
        </Grid.Col>

        <Grid.Col span={{ base: 12, md: 5 }}>
          <Box style={{ height: 380, border: "1px solid var(--color-border)" }} data-testid="analysis-home-map">
            <CrisisMap
              center={config?.center ?? [10, 20]}
              zoom={4.5}
              className="w-full h-full"
              focusCountryPCode={config?.pCode}
              focusCountryName={countryName}
              regions={regions}
            />
          </Box>
          {created.length > 0 && (
            <Text c="var(--color-text-muted)" mt={8} style={{ fontSize: 12 }}>
              {t("mapNote")}
            </Text>
          )}
        </Grid.Col>
      </Grid>
    </Box>
  );
}

function GroupLabel({ children }: { children: ReactNode }) {
  return (
    <Text fw={700} tt="uppercase" c="var(--color-text-secondary)" mb={8} style={{ fontSize: 11, letterSpacing: "0.08em" }}>
      {children}
    </Text>
  );
}

function ScopeRow({
  title,
  subtitle,
  status,
  stale,
  generating,
  onOpen,
  action,
  testId,
}: {
  title: string;
  subtitle: string;
  status: string;
  stale: boolean;
  generating?: boolean;
  onOpen: () => void;
  action?: ReactNode;
  testId: string;
}) {
  const t = useTranslations("analysis.home");
  return (
    <Box
      style={{ display: "flex", alignItems: "center", border: "1px solid var(--color-border)", background: "var(--color-bg-white)" }}
      data-testid={testId}
    >
      <UnstyledButton
        onClick={onOpen}
        px={16}
        py={14}
        className="hover:bg-[var(--color-bg-muted)]"
        style={{ flex: 1, minWidth: 0, display: "flex", alignItems: "center", gap: 12 }}
      >
        <Box style={{ flex: 1, minWidth: 0 }}>
          <Group gap={8} wrap="nowrap">
            <Text fw={700} c="var(--color-text-primary)" truncate style={{ fontSize: 15 }}>
              {title}
            </Text>
            {stale && (
              <Badge size="xs" radius="sm" style={{ background: "var(--color-warning-light)", color: "var(--color-warning)", flexShrink: 0 }}>
                {t("stale")}
              </Badge>
            )}
          </Group>
          <Text c="var(--color-text-secondary)" mt={2} style={{ fontSize: 12 }}>
            {subtitle}
          </Text>
          <Text c={generating ? "var(--color-info)" : "var(--color-text-muted)"} mt={2} style={{ fontSize: 12 }}>
            {status}
          </Text>
        </Box>
        <IconChevronRight size={16} color="var(--color-text-muted)" style={{ flexShrink: 0 }} />
      </UnstyledButton>
      {action && <Box px={12}>{action}</Box>}
    </Box>
  );
}
